Update S95majestic

diff --git a/devices/ssc338q_apfpv/general/overlay/etc/init.d/S95majestic b/devices/ssc338q_apfpv/general/overlay/etc/init.d/S95majestic
--- a/devices/ssc338q_apfpv/general/overlay/etc/init.d/S95majestic
+++ b/devices/ssc338q_apfpv/general/overlay/etc/init.d/S95majestic
@@ -5,47 +5,43 @@ PIDFILE="/var/run/$DAEMON.pid"
 DAEMON_ARGS="-s"
 
 start() {
-        kill -9 $(pidof majestic)
-        echo -n "Starting $DAEMON: "
-        start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "$DAEMON" -- $DAEMON_ARGS
-        if [ $? -eq 0 ]; then
-                echo "OK"
-        else
-                echo "FAIL"
-        fi
+	echo -n "Starting $DAEMON: "
+	start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "$DAEMON" -- $DAEMON_ARGS
+	if [ $? -eq 0 ]; then
+		echo "OK"
+	else
+		echo "FAIL"
+	fi
 }
 
 stop() {
-        echo -n "Stopping $DAEMON: "
-        start-stop-daemon -K -q -p "$PIDFILE"
-        if [ $? -eq 0 ]; then
-                rm -f "$PIDFILE"
-                echo "OK"
-        else
-                echo "FAIL"
-        fi
-        kill -9 $(pidof majestic)
+	echo -n "Stopping $DAEMON: "
+	start-stop-daemon -K -q -p "$PIDFILE"
+	if [ $? -eq 0 ]; then
+		rm -f "$PIDFILE"
+		echo "OK"
+	else
+		echo "FAIL"
+	fi
 }
 
 case "$1" in
-        start)
-                $1
-                ;;
-        stop)
-                killall -9 $(pidof majestic)
-                ;;
-        restart)
-                stop
-                sleep 3
-                start
-                ;;
+	start|stop)
+		$1
+		;;
 
-        reload)
-                killall -1 "$DAEMON"
-                ;;
+	restart)
+		stop
+		sleep 3
+		start
+		;;
 
-        *)
-                echo "Usage: $0 {start|stop|restart|reload}"
-                exit 1
-                ;;
+	reload)
+		killall -1 "$DAEMON"
+		;;
+
+	*)
+		echo "Usage: $0 {start|stop|restart|reload}"
+		exit 1
+		;;
 esac
